### PR TITLE
returnpath: not empty check vs trying to count non countable

### PR DESCRIPTION
**Pull request by kornrunner**
This check is better, and doesn't issue notice on PHP 7.2.

Please consider merging it in, and releasing minor version afterwards. Thank you!

### CODE REVIEW

**Comment by kornrunner** [comment]
Bump?

**Comment by xaphan42** [comment]
Sorry for the delay!

**Comment by kornrunner** [comment]
Thank you! Any chance of tagging a release too?

**Comment by xaphan42** [comment]
I just tagged master. I figure that's a good starting point. Then we can increase the version as needed with future commits. Thanks!

**Pull request merged**
